name: shell commands

on:[push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
    # array of objects
      - name: echo a string
        run: echo " HELLO"
      - name: Multiline script
        run: |
          node -v
          npm -v
